package io.zrz.hai.runtime.engine;

import io.zrz.hai.runtime.ZValue;

/**
 * receives results generated by execution, and returns them, to the client as
 * they are available, and based on client configuration.
 *
 * The primary result set is returned when all immediate dependencies are
 * resolved. After that, deferred results are generated.
 *
 * The results are delivered with an identifier that indicates where in the
 * output set they are.
 *
 * as processing progresses, branches are opened on points in the result set.
 *
 */

public interface EHistoricResultCollector {

  void write(String name, ZValue val);

  void write(String outputName, String value);

  void write(String outputName, int count);

  void writeNull(String name);

  void writeStartArray(String outputName);

  void writeStartObject();

  void writeEnd();

  void writeStartObject(String outputName);

  void writeStartData();

  void writeEndData();

  void close();

}
